import {
  IoIosArrowDown,
  IoIosArrowForward,
  IoIosHeartEmpty,
} from "react-icons/io";
import { CgProductHunt } from "react-icons/cg";
import { IoBatteryDeadOutline } from "react-icons/io5";
import { IoIosArrowUp } from "react-icons/io";
import General from "../../../public/bybenefitIocn/general.svg";
import MensHelth from "../../../public/bybenefitIocn/mens-health.svg";
import CapsuleIicon01 from "../../../public/get-started-page-img/capsule-icon-1.webp";
import GroupPage from "../../../public/get-started-page-img/GroupPage.webp";
import BundlesBanner from "../../../public/bundlesBanner/bundlesBanner.webp";

export const ProductFilterMenuArray = [
  { id: "01", title: "The Daily 4" },
  { id: "02", title: "New" },
  { id: "03", title: "Best Sellers" },
  { id: "04", title: "Value Packs" },
  { id: "05", title: "Wellblends" },
];

export const MenuItemsArray = [
  { label: "Products", category: "products" },
  { label: "Find vitamins for me", category: "findVitamins" },
  { label: "Tips & Resources", category: "tipsResources" },
  { label: "About", category: "about" },
];

export const ProductsArray = [
  // wellblends wellblends wellblends wellblends
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "wellblends",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "wellblends",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "wellblends",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  // new new new new new new
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "new",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "new",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "new",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  // best_seller best_seller best_seller
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "slip longer",
    nameSubtruc: "",
    productTitle: "WELLBLENDS™",
    cetagory: "best_seller",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "best_seller",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },

  // value_pack value_pack value_pack
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "value_pack",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "value_pack",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },

  // the_daily_4 the_daily_4 the_daily_4 the_daily_4
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "the_daily_4",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
];

export const AdvertiesArray = [
  {
    id: 1,
    heading: "What Vitamins Should I Take?",
    description:
      "Our guide helps you understand the essential nutrients your body needs and find the right supplements to support your health goals. From multivitamins to targeted minerals, we've got you covered.",
    btnText: "contineu reading",
    image: "/image/adverties01.webp",
  },
  {
    id: 2,
    heading: "Your Daily Dose of Wellness: Introducing The Daily 4™",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties02.webp",
  },
  {
    id: 3,
    heading: "5 Key Immune Support Vitamins and Minerals You May Be Missing",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties03.webp",
  },
  {
    id: 4,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
  {
    id: 5,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
  {
    id: 6,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
  {
    id: 7,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
];

export const CompaniesLogoAndServiceArray = [
  {
    id: 1,
    logo: "/companies-logo/partnership-cplmpanies-logo01.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image01.webp",
    serviceBtn: "our exparties",
  },
  {
    id: 2,
    logo: "/companies-logo/partnership-cplmpanies-logo02.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image02.webp",
    serviceBtn: "Our brands",
  },
  {
    id: 3,
    logo: "/companies-logo/partnership-cplmpanies-logo03.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image03.webp",
    serviceBtn: "our histoey",
  },
  {
    id: 4,
    logo: "/companies-logo/partnership-cplmpanies-logo02.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image03.webp",
    serviceBtn: "our exparties",
  },
  {
    id: 5,
    logo: "/companies-logo/partnership-cplmpanies-logo03.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image03.webp",
    serviceBtn: "our exparties",
  },
];
export const BackedByScienceArray = [
  {
    id: 1,
    image: "/BackedByScience/BackedByScience01.webp",
    linkTitle: "magnesium",
    cetagory: "magnesium",
  },
  {
    id: 2,
    image: "/BackedByScience/BackedByScience02.webp",
    linkTitle: "b vitamins",
    cetagory: "b vitamins",
  },
  {
    id: 3,
    image: "/BackedByScience/BackedByScience03.webp",
    linkTitle: "d vitamins",
    cetagory: "d vitamins",
  },
  {
    id: 4,
    image: "/BackedByScience/BackedByScience04.webp",
    linkTitle: "multivitamins",
    cetagory: "multivitamins",
  },
];
export const SearchInputValueArray = [
  {
    id: 1,
    title: "Start a Regimen",
  },
  {
    id: 2,
    title: "Coupons",
  },
  {
    id: 3,
    title: "Where to Start",
  },
  {
    id: 4,
    title: "Men's Health",
  },
  {
    id: 5,
    title: "Women’s Health",
  },
  {
    id: 6,
    title: "What Should I Take?",
  },
  {
    id: 7,
    title: "Gummies",
  },
  {
    id: 8,
    title: "Multivitamins",
  },
  {
    id: 9,
    title: "Best Sellers",
  },
];
export const ProductItemcetagoryArray = [
  {
    id: 1,
    title: "a - z",
    forwardAwwos: <IoIosArrowForward />,
  },
  {
    id: 2,
    title: "by benefit",
    forwardAwwos: <IoIosArrowForward />,
  },
  {
    id: 3,
    title: "gummies",
    forwardAwwos: <IoIosArrowForward />,
  },
  {
    id: 4,
    title: "best seller",
    forwardAwwos: false,
  },
  {
    id: 5,
    title: "new product",
    forwardAwwos: false,
  },
  {
    id: 6,
    title: "bunlde & save",
    forwardAwwos: false,
  },
  {
    id: 7,
    title: "subscribe & save",
    forwardAwwos: false,
  },
  {
    id: 8,
    title: "view all",
    forwardAwwos: false,
  },
];
export const ByBenefitArray = [
  {
    id: 1,
    title: " Beauty ",
    byBenifitIcon: "/bybenefitIocn/beauty.svg",
  },
  {
    id: 2,
    title: " Bone  ",
    byBenifitIcon: "/bybenefitIocn/bone.svg",
  },
  {
    id: 3,
    title: " Brain ",
    byBenifitIcon: "/bybenefitIocn/PHA-1853-Brain-(33px).svg",
  },
  {
    id: 4,
    title: " Digestion ",
    byBenifitIcon: "/bybenefitIocn/digestion.svg",
  },
  {
    id: 5,
    title: "Energy ",
    byBenifitIcon: "/bybenefitIocn/energy.svg",
  },
  {
    id: 6,
    title: " Eye Health ",
    byBenifitIcon: "/bybenefitIocn/eye.svg",
  },
  {
    id: 7,
    title: " General Wellness ",
    byBenifitIcon: "/bybenefitIocn/general.svg",
  },
  {
    id: 8,
    title: " Immune Health  ",
    byBenifitIcon: "/bybenefitIocn/beauty.svg",
  },
  {
    id: 9,
    title: "  Joints  ",
    byBenifitIcon: "/bybenefitIocn/joint.svg",
  },
  {
    id: 10,
    title: " Kids  ",
    byBenifitIcon: "/bybenefitIocn/kids.svg",
  },
  {
    id: 11,
    title: " Men's Health   ",
    byBenifitIcon: "/bybenefitIocn/mens-health.svg",
  },
  {
    id: 12,
    title: "  Mood  ",
    byBenifitIcon: "/bybenefitIocn/mood.svg",
  },
  {
    id: 13,
    title: "  Prenatal & Postnatal  ",
    byBenifitIcon: "/bybenefitIocn/beauty.svg",
  },
  {
    id: 14,
    title: "  Sleep  ",
    byBenifitIcon: "/bybenefitIocn/sleep.svg",
  },
  {
    id: 15,
    title: " Stress  ",
    byBenifitIcon: "/bybenefitIocn/stress.svg",
  },
  {
    id: 16,
    title: " Women's Health   ",
    byBenifitIcon: "/bybenefitIocn/womens-health.svg",
  },
  {
    id: 16,
    title: " Heart ",
    byBenifitIcon: "/bybenefitIocn/heart.svg",
  },
];
export const GetStartedBannerArray = [
  {
    id: 1,
    subHeading: "Your journey begins here",
    heading: "What Do I Need?",
    paragraph: "Not sure which supplements to take? We’re here to help.",
    bgImage: "/get-started-page-img/get-sterted-banner.jpg",
    bgImageMobile: "/get-started-page-img/get-started-banner-mobile.webp",
  },
];
export const BundlesBannerArray = [
  {
    id: 1,
    subHeading: "Bundle And Save 20%",
    heading: "Value Packs",
    paragraph:
      "Nature Made® value packs bundle products into one convenient shipment at a discount.†",
    bgImage: BundlesBanner,
    bgImageMobile: "/get-started-page-img/get-started-banner-mobile.webp",
  },
];
export const HowToGetStartedArray = [
  {
    id: 1,
    subHeading:
      "Browse some common health needs to see which ones may apply to you.",
    heading: "Quick Start Recommendations",
    buttonText: "Get Started",
    logos: "/get-started-page-img/bottolTablet01.webp",
  },
  {
    id: 2,
    subHeading: "Learn more about dietary supplements and their benefits.",
    heading: "Vitamins 101",
    buttonText: "Explore More",
    logos: "/get-started-page-img/ShapeFlag01.webp",
  },
  {
    id: 3,
    subHeading:
      "Take the guesswork out of wellness with a regimen chosen by our experts.",
    heading: "Your Daily 4",
    buttonText: "start today",
    logos: "/get-started-page-img/callenderLogo01.svg",
  },
];
export const Vitamins101Array = [
  {
    id: 1,
    heading: "Why should I take vitamins?",
    paragrap:
      "We get it, life gets busy. We might not always stop to think about our wellness. How can we ensure we’re getting enough of the essential nutrients we need from our food? What if sometimes our wellbeing needs a little extra support? Supplementing with vitamins, minerals and other nutrients can help support your nutritional needs so that you can focus on everything else.†",
    buttonTextLess: "SHOW LESS",
    buttonTextMore: "SHOW MORE",
    logos: General,
    // logos: "/bybenefitIocn/general.svg",
  },
  {
    id: 2,
    heading: "How do vitamins & supplements support my wellness?",
    paragrap:
      "Many vitamins and minerals are considered essential, meaning you need to consume them (from food) every day. Why? Every system in your body, from your immune system and nervous system to your heart, muscles, and bones, relies on essential nutrients to function properly. Yet many adults are not getting the recommended amounts of these essential nutrients from food alone.[1] This is where dietary supplements come in. They help provide these nutrients (like Vitamins C and D, B Vitamins, Magnesium, and Zinc) so that you can help close nutrient gaps that may exist in your diet.†",
    buttonTextLess: "SHOW LESS",
    buttonTextMore: "SHOW MORE",
    logos: CapsuleIicon01,
    // logos: "/get-started-page-img/capsule-icon-1.webp",
  },
  {
    id: 3,
    heading: "Where do I begin?",
    paragrap:
      "While many of us might benefit from dietary supplements, we all have different needs and at different times. Nature Made®️ has you covered with vitamins and supplements for everyone at every life stage. Whether it's multivitamins for daily nutritional support, nutrients that support your bone, muscle, heart and immune health, or ingredients that support your mood, stress and occasional sleep needs. And you can choose between tablets, softgels, capsules, tasty chewables and delicious gummies. No matter your choice, it's easy to switch up your routine as your needs change.†",
    buttonTextLess: "SHOW LESS",
    buttonTextMore: "SHOW MORE",
    logos: GroupPage,
    // logos: "/get-started-page-img/GroupPage.webp",
  },
];
export const GetStartedQuestionArray = [
  {
    id: 1,
    heading: "What vitamins and supplements should I take?",
    article:
      "The best way to support your daily nutrition is to eat a well-balanced diet that consists of fruit, vegetables, whole grains, healthy fats and lean meats. This is your go-to for the vitamins, minerals and nutrients your body needs every day. However, we know that in today’s busy world, that’s not always possible. Dietary supplements, such as multivitamins, are designed to help support your daily nutrition and provide the nutrients your body needs to function at its best. You should first consult with your healthcare provider before adding any dietary supplement to your routine.†",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
  {
    id: 2,
    heading:
      "Are Nature Made Gummies gluten free? Do they use artificial colors and/or flavors? What about their sugar content?",
    article:
      "Most Nature Made Adult Gummies are gluten free and only use natural flavors and colors derived from natural sources (no synthetic dyes). Our gummies contain approximately 1–3 grams of sugar and 5–15 calories per gummy. When consumed as part of a healthy diet, this amount should not be a concern. Please refer to the label for your product's calorie and sugar content. If you are sensitive to sugar, please check with a healthcare professional about incorporating gummies into your daily plan.",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
  {
    id: 3,
    heading: "What do multivitamins help with?",
    article:
      "Multivitamins help fill potential nutrient gaps from your diet by providing daily nutritional support.†",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
  {
    id: 4,
    heading: "How do I know if I need to supplement with vitamin D?",
    article:
      "Your personal healthcare professional can order a simple blood test to check your vitamin D levels. You may be at risk if you: • Experience less than 15-30 minutes of full body exposure sunlight between 10 a.m. and 3 p.m. • Wear sunscreen. • Have a darker hue of skin color. • Are over 65 years of age. • Spend most of your time indoors. • Live in a region with a long winter season. • Are overweight or obese.",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
  {
    id: 5,
    heading: "What does fish oil do for the body?",
    article:
      "Fish Oil contains the Omega-3 Fatty Acids Eicosapentaenoic Acid (EPA) and Docosahexaenoic Acid (DHA) that help support heart health, brain health and eye health. However, the body does not make EPA and DHA on its own, so it is best to get these nutrients from food sources.[2] Since not everyone regularly consumes fatty fish, an Omega-3†† from fish oil supplement can provide the body with Omega-3s.[1]†",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
  {
    id: 6,
    heading: "Should I take a magnesium supplement?",
    article:
      "If your diet is lacking in magnesium-rich foods, a magnesium supplement may be a good choice to ensure your magnesium needs are met. Some people need magnesium supplements due to certain medications or health conditions. Talk to your healthcare professional to determine if a magnesium supplement fits into your supplement regimen.",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
  {
    id: 7,
    heading: "Why should I start a subscription?",
    article:
      "It's Easy & Flexible Set it and forget it. You can change, pause, and cancel anytime. Membership Exclusive Get 10% discount on every order plus free shipping**. Learn More **When you purchase one or more products on subscription, you will automatically get free shipping on this and all future deliveries. Offer excludes tax and is subject to change. Orders outside of the contiguous US, including Alaska & Hawaii will be charged $8 for shipping.",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
];
export const CardForGetStartedPageArray = [
  {
    id: 1,
    favorites: "",
    baseName: "Energy",
    nameSubtruc: "",
    productTitle: "",
    cetagory: "collections",
    review: "",
    reviewPerson: "",
    isNew: "",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "",
    productIconGen: General,
    productIconVit: MensHelth,
    doseType: "3-in-1 Blend",
    doseIcon: "",
    price: "",
    buyBtn: "Shop now",
  },
  {
    id: 2,
    favorites: "",
    baseName: "Energy",
    nameSubtruc: "",
    productTitle: "",
    cetagory: "collections",
    review: "",
    reviewPerson: "",
    isNew: "",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "",
    productIconGen: General,
    productIconVit: MensHelth,
    doseType: "3-in-1 Blend",
    doseIcon: "",
    price: "",
    buyBtn: "Shop now",
  },
  {
    id: 3,
    favorites: "",
    baseName: "Energy",
    nameSubtruc: "",
    productTitle: "",
    cetagory: "collections",
    review: "",
    reviewPerson: "",
    isNew: "",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "",
    productIconGen: General,
    productIconVit: MensHelth,
    doseType: "3-in-1 Blend",
    doseIcon: "",
    price: "",
    buyBtn: "Shop now",
    mensMultivitamins: "multivitamins",
  },

  {
    id: 4,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "You may also like",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIconGen: General,
    productIconVit: MensHelth,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },

  {
    id: 5,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "You may also like",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 6,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "You may also like",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 7,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "You may also like",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 8,
    favorites: "",
    baseName: "Energy",
    nameSubtruc: "",
    productTitle: "",
    cetagory: "collections",
    review: "",
    reviewPerson: "",
    isNew: "",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "",
    productIconGen: General,
    productIconVit: MensHelth,
    doseType: "3-in-1 Blend",
    doseIcon: "",
    price: "",
    buyBtn: "Shop now",
  },
];
export const GetStartedExploreArray = [
  {
    id: 1,
    heading: "What Vitamins Should I Take?",
    article:
      "If you’re asking, what vitamins should I take daily? Don’t worry, Nature Made® is here to help! There are 13 essential vitamins that your body needs every day to function at its best: vitamins A, C, D, E, K and the eight B vitamins (including Folic Acid, Biotin, B6 and B12). What does a vitamin do? Along with other essential nutrients, vitamins play an important role in many bodily functions. Vitamins need to be consumed from food; however, it can be difficult to consume enough from your diet alone. That’s where supplements come in—they can help support your daily nutritional needs.†",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
  {
    id: 2,
    heading: "What Supplements Should I Take?",
    article:
      "There is more to daily nutrition than just vitamins. There are many different minerals and nutrients that also help support your health and wellbeing. Essential minerals, such as Magnesium, Calcium and Iron, are needed by your body for a variety of functions. Nutrients like Choline and CoQ10 are important for your brain health and heart health, respectively. You can search here on our website by benefit to find the nutrients to help support your specific needs.†",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
  {
    id: 3,
    heading: "Nature Made Vitamins and Supplements",
    article:
      "Nature Made® has been a lead innovator of science-backed wellness solutions for over fifty years. That’s what makes us the #1 Pharmacist Recommended Vitamin and Supplement Brand.* As always, be sure to first check with your healthcare provider before adding any new vitamin or supplement to your daily routine.",
    upArrow: <IoIosArrowUp />,
    downArrow: <IoIosArrowDown />,
  },
];
