import { IoIosArrowForward, IoIosHeartEmpty } from "react-icons/io";
import { CgProductHunt } from "react-icons/cg";
import { IoBatteryDeadOutline } from "react-icons/io5";

export const productFilterMenu = [
  { id: "01", title: "The Daily 4" },
  { id: "02", title: "New" },
  { id: "03", title: "Best Sellers" },
  { id: "04", title: "Value Packs" },
  { id: "05", title: "Wellblends" },
];

export const menuItems = [
  { label: "Products", category: "products" },
  { label: "Find vitamins for me", category: "findVitamins" },
  { label: "Tips & Resources", category: "tipsResources" },
  { label: "About", category: "about" },
];

export const products = [
  // wellblends wellblends wellblends wellblends
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "wellblends",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "wellblends",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "wellblends",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  // new new new new new new
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "new",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "new",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "new",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  // best_seller best_seller best_seller
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "slip longer",
    nameSubtruc: "",
    productTitle: "WELLBLENDS™",
    cetagory: "best_seller",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "best_seller",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },

  // value_pack value_pack value_pack
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "value_pack",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "value_pack",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },

  // the_daily_4 the_daily_4 the_daily_4 the_daily_4
  {
    id: 1,
    favorites: <IoIosHeartEmpty />,
    nameBase: "Energy",
    nameSubtruc: "MAX™",
    productTitle: "WELLBLENDS™",
    cetagory: "the_daily_4",
    review: "★★★★☆",
    reviewPerson: 59,
    isNew: "new",
    onlineAvilable: "Online Avilable",
    discount: "30%",
    bestSeller: "Best Seller",
    image: "/image/energy-max.webp",
    productType: "gummies",
    productIcon: <CgProductHunt />,
    doseType: "3-in-1 Blend",
    doseIcon: <IoBatteryDeadOutline />,
    price: "99",
    buyBtn: "buy now",
  },
];

export const adverties = [
  {
    id: 1,
    heading: "What Vitamins Should I Take?",
    description:
      "Our guide helps you understand the essential nutrients your body needs and find the right supplements to support your health goals. From multivitamins to targeted minerals, we've got you covered.",
    btnText: "contineu reading",
    image: "/image/adverties01.webp",
  },
  {
    id: 2,
    heading: "Your Daily Dose of Wellness: Introducing The Daily 4™",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties02.webp",
  },
  {
    id: 3,
    heading: "5 Key Immune Support Vitamins and Minerals You May Be Missing",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties03.webp",
  },
  {
    id: 4,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
  {
    id: 5,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
  {
    id: 6,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
  {
    id: 7,
    heading: "Magnesium for Muscles: How It Supports Muscle Health",
    description: "products",
    btnText: "contineu reading",
    image: "/image/adverties04.webp",
  },
];

export const companiesLogoAndService = [
  {
    id: 1,
    logo: "/companies-logo/partnership-cplmpanies-logo01.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image01.webp",
    serviceBtn: "our exparties",
  },
  {
    id: 2,
    logo: "/companies-logo/partnership-cplmpanies-logo02.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image02.webp",
    serviceBtn: "Our brands",
  },
  {
    id: 3,
    logo: "/companies-logo/partnership-cplmpanies-logo03.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image03.webp",
    serviceBtn: "our histoey",
  },
  {
    id: 4,
    logo: "/companies-logo/partnership-cplmpanies-logo02.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image03.webp",
    serviceBtn: "our exparties",
  },
  {
    id: 5,
    logo: "/companies-logo/partnership-cplmpanies-logo03.webp",
    title: "products",
    servicesImg: "/companies-logo/services-image03.webp",
    serviceBtn: "our exparties",
  },
];
export const backedByScience = [
  {
    id: 1,
    image: "/BackedByScience/BackedByScience01.webp",
    linkTitle: "magnesium",
    cetagory: "magnesium",
  },
  {
    id: 2,
    image: "/BackedByScience/BackedByScience02.webp",
    linkTitle: "b vitamins",
    cetagory: "b vitamins",
  },
  {
    id: 3,
    image: "/BackedByScience/BackedByScience03.webp",
    linkTitle: "d vitamins",
    cetagory: "d vitamins",
  },
  {
    id: 4,
    image: "/BackedByScience/BackedByScience04.webp",
    linkTitle: "multivitamins",
    cetagory: "multivitamins",
  },
];
export const searchInputValue = [
  {
    id: 1,
    title: "Start a Regimen",
  },
  {
    id: 2,
    title: "Coupons",
  },
  {
    id: 3,
    title: "Where to Start",
  },
  {
    id: 4,
    title: "Men's Health",
  },
  {
    id: 5,
    title: "Women’s Health",
  },
  {
    id: 6,
    title: "What Should I Take?",
  },
  {
    id: 7,
    title: "Gummies",
  },
  {
    id: 8,
    title: "Multivitamins",
  },
  {
    id: 9,
    title: "Best Sellers",
  },
];
export const productItemcetagory = [
  {
    id: 1,
    title: "a - z",
    forwardAwwos: <IoIosArrowForward />,
  },
  {
    id: 2,
    title: "by benefit",
    forwardAwwos: <IoIosArrowForward />,
  },
  {
    id: 3,
    title: "gummies",
    forwardAwwos: <IoIosArrowForward />,
  },
  {
    id: 4,
    title: "best seller",
    forwardAwwos: false,
  },
  {
    id: 5,
    title: "new product",
    forwardAwwos: false,
  },
  {
    id: 6,
    title: "bunlde & save",
    forwardAwwos: false,
  },
  {
    id: 7,
    title: "subscribe & save",
    forwardAwwos: false,
  },
  {
    id: 8,
    title: "view all",
    forwardAwwos: false,
  },
];
export const byBenefitArr = [
  {
    id: 1,
    title: " Beauty ",
    byBenifitIcon: "/bybenefitIocn/beauty.svg",
  },
  {
    id: 2,
    title: " Bone  ",
    byBenifitIcon: "/bybenefitIocn/bone.svg",
  },
  {
    id: 3,
    title: " Brain ",
    byBenifitIcon: "/bybenefitIocn/PHA-1853-Brain-(33px).svg",
  },
  {
    id: 4,
    title: " Digestion ",
    byBenifitIcon: "/bybenefitIocn/digestion.svg",
  },
  {
    id: 5,
    title: "Energy ",
    byBenifitIcon: "/bybenefitIocn/energy.svg",
  },
  {
    id: 6,
    title: " Eye Health ",
    byBenifitIcon: "/bybenefitIocn/eye.svg",
  },
  {
    id: 7,
    title: " General Wellness ",
    byBenifitIcon: "/bybenefitIocn/general.svg",
  },
  {
    id: 8,
    title: " Immune Health  ",
    byBenifitIcon: "/bybenefitIocn/beauty.svg",
  },
  {
    id: 9,
    title: "  Joints  ",
    byBenifitIcon: "/bybenefitIocn/joint.svg",
  },
  {
    id: 10,
    title: " Kids  ",
    byBenifitIcon: "/bybenefitIocn/kids.svg",
  },
  {
    id: 11,
    title: " Men's Health   ",
    byBenifitIcon: "/bybenefitIocn/mens-health.svg",
  },
  {
    id: 12,
    title: "  Mood  ",
    byBenifitIcon: "/bybenefitIocn/mood.svg",
  },
  {
    id: 13,
    title: "  Prenatal & Postnatal  ",
    byBenifitIcon: "/bybenefitIocn/beauty.svg",
  },
  {
    id: 14,
    title: "  Sleep  ",
    byBenifitIcon: "/bybenefitIocn/sleep.svg",
  },
  {
    id: 15,
    title: " Stress  ",
    byBenifitIcon: "/bybenefitIocn/stress.svg",
  },
  {
    id: 16,
    title: " Women's Health   ",
    byBenifitIcon: "/bybenefitIocn/womens-health.svg",
  },
  {
    id: 16,
    title: " Heart ",
    byBenifitIcon: "/bybenefitIocn/heart.svg",
  },
];
